### ISSUE TITLE
java -jar xJavaFxTool-0.3.2.jar 启动失败

### ISSUE THREAD

**Issue by AndyWu2015** [864381832/xJavaFxTool#27]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/xwintop/xJavaFxTool/XJavaFxToolMain has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by AndyWu2015** [comment]
本地环境时java7或者java8都不能启动

**Comment by yiding-he** [comment]
请参考这里：
https://cn.bing.com/search?q=java.lang.UnsupportedClassVersionError+61.0&setmkt=zh-CN&PC=EMMX01&form=LWS002&scope=web

Andy Wu ***@***.***> 于 2023年4月14日周五 21:11写道：
